package iso3166_1

var Country_name_ja = map[string]string{
	"IS":"アイスランド",
	"IE":"アイルランド",
	"AZ":"アゼルバイジャン",
	"AF":"アフガニスタン",
	"US":"アメリカ合衆国",
	"VI":"アメリカ領ヴァージン諸島",
	"AS":"アメリカ領サモア",
	"AE":"アラブ首長国連邦",
	"DZ":"アルジェリア",
	"AR":"アルゼンチン",
	"AW":"アルバ",
	"AL":"アルバニア",
	"AM":"アルメニア",
	"AI":"アンギラ",
	"AO":"アンゴラ",
	"AG":"アンティグア・バーブーダ",
	"AD":"アンドラ",
	"YE":"イエメン",
	"GB":"イギリス",
	"IO":"イギリス領インド洋地域",
	"VG":"イギリス領ヴァージン諸島",
	"IL":"イスラエル",
	"IT":"イタリア",
	"IQ":"イラク",
	"IR":"イラン|イラン・イスラム共和国",
	"IN":"インド",
	"ID":"インドネシア",
	"WF":"ウォリス・フツナ",
	"UG":"ウガンダ",
	"UA":"ウクライナ",
	"UZ":"ウズベキスタン",
	"UY":"ウルグアイ",
	"EC":"エクアドル",
	"EG":"エジプト",
	"EE":"エストニア",
	"ET":"エチオピア",
	"ER":"エリトリア",
	"SV":"エルサルバドル",
	"AU":"オーストラリア",
	"AT":"オーストリア",
	"AX":"オーランド諸島",
	"OM":"オマーン",
	"NL":"オランダ",
	"GH":"ガーナ",
	"CV":"カーボベルデ",
	"GG":"ガーンジー",
	"GY":"ガイアナ",
	"KZ":"カザフスタン",
	"QA":"カタール",
	"UM":"合衆国領有小離島",
	"CA":"カナダ",
	"GA":"ガボン",
	"CM":"カメルーン",
	"GM":"ガンビア",
	"KH":"カンボジア",
	"MP":"北マリアナ諸島",
	"GN":"ギニア",
	"GW":"ギニアビサウ",
	"CY":"キプロス",
	"CU":"キューバ",
	"CW":"キュラソー島|キュラソー",
	"GR":"ギリシャ",
	"KI":"キリバス",
	"KG":"キルギス",
	"GT":"グアテマラ",
	"GP":"グアドループ",
	"GU":"グアム",
	"KW":"クウェート",
	"CK":"クック諸島",
	"GL":"グリーンランド",
	"CX":"クリスマス島 (オーストラリア)|クリスマス島",
	"GE":"グルジア",
	"GD":"グレナダ",
	"HR":"クロアチア",
	"KY":"ケイマン諸島",
	"KE":"ケニア",
	"CI":"コートジボワール",
	"CC":"ココス諸島|ココス（キーリング）諸島",
	"CR":"コスタリカ",
	"KM":"コモロ",
	"CO":"コロンビア",
	"CG":"コンゴ共和国",
	"CD":"コンゴ民主共和国",
	"SA":"サウジアラビア",
	"GS":"サウスジョージア・サウスサンドウィッチ諸島",
	"WS":"サモア",
	"ST":"サントメ・プリンシペ",
	"BL":"サン・バルテルミー島|サン・バルテルミー",
	"ZM":"ザンビア",
	"PM":"サンピエール島・ミクロン島",
	"SM":"サンマリノ",
	"MF":"サン・マルタン (西インド諸島)|サン・マルタン（フランス領）",
	"SL":"シエラレオネ",
	"DJ":"ジブチ",
	"GI":"ジブラルタル",
	"JE":"ジャージー",
	"JM":"ジャマイカ",
	"SY":"シリア|シリア・アラブ共和国",
	"SG":"シンガポール",
	"SX":"シント・マールテン|シント・マールテン（オランダ領）",
	"ZW":"ジンバブエ",
	"CH":"スイス",
	"SE":"スウェーデン",
	"SD":"スーダン",
	"SJ":"スヴァールバル諸島およびヤンマイエン島",
	"ES":"スペイン",
	"SR":"スリナム",
	"LK":"スリランカ",
	"SK":"スロバキア",
	"SI":"スロベニア",
	"SZ":"スワジランド",
	"SC":"セーシェル",
	"GQ":"赤道ギニア",
	"SN":"セネガル",
	"RS":"セルビア",
	"KN":"セントクリストファー・ネイビス",
	"VC":"セントビンセント・グレナディーン|セントビンセントおよびグレナディーン諸島",
	"SH":"セントヘレナ・アセンションおよびトリスタンダクーニャ",
	"LC":"セントルシア",
	"SO":"ソマリア",
	"SB":"ソロモン諸島",
	"TC":"タークス・カイコス諸島",
	"TH":"タイ王国|タイ",
	"KR":"大韓民国",
	"TW":"台湾",
	"TJ":"タジキスタン",
	"TZ":"タンザニア",
	"CZ":"チェコ",
	"TD":"チャド",
	"CF":"中央アフリカ共和国",
	"CN":"中華人民共和国|中国",
	"TN":"チュニジア",
	"KP":"朝鮮民主主義人民共和国",
	"CL":"チリ",
	"TV":"ツバル",
	"DK":"デンマーク",
	"DE":"ドイツ",
	"TG":"トーゴ",
	"TK":"トケラウ",
	"DO":"ドミニカ共和国",
	"DM":"ドミニカ国",
	"TT":"トリニダード・トバゴ",
	"TM":"トルクメニスタン",
	"TR":"トルコ",
	"TO":"トンガ",
	"NG":"ナイジェリア",
	"NR":"ナウル",
	"NA":"ナミビア",
	"AQ":"南極",
	"NU":"ニウエ",
	"NI":"ニカラグア",
	"NE":"ニジェール",
	"JP":"日本",
	"EH":"西サハラ",
	"NC":"ニューカレドニア",
	"NZ":"ニュージーランド",
	"NP":"ネパール",
	"NF":"ノーフォーク島",
	"NO":"ノルウェー",
	"HM":"ハード島とマクドナルド諸島",
	"BH":"バーレーン",
	"HT":"ハイチ",
	"PK":"パキスタン",
	"VA":"バチカン|バチカン市国",
	"PA":"パナマ",
	"VU":"バヌアツ",
	"BS":"バハマ",
	"PG":"パプアニューギニア",
	"BM":"バミューダ諸島|バミューダ",
	"PW":"パラオ",
	"PY":"パラグアイ",
	"BB":"バルバドス",
	"PS":"パレスチナ",
	"HU":"ハンガリー",
	"BD":"バングラデシュ",
	"TL":"東ティモール",
	"PN":"ピトケアン諸島|ピトケアン",
	"FJ":"フィジー",
	"PH":"フィリピン",
	"FI":"フィンランド",
	"BT":"ブータン",
	"BV":"ブーベ島",
	"PR":"プエルトリコ",
	"FO":"フェロー諸島",
	"FK":"フォークランド諸島|フォークランド（マルビナス）諸島",
	"BR":"ブラジル",
	"FR":"フランス",
	"GF":"フランス領ギアナ",
	"PF":"フランス領ポリネシア",
	"TF":"フランス領南方・南極地域",
	"BG":"ブルガリア",
	"BF":"ブルキナファソ",
	"BN":"ブルネイ|ブルネイ・ダルサラーム",
	"BI":"ブルンジ",
	"VN":"ベトナム",
	"BJ":"ベナン",
	"VE":"ベネズエラ|ベネズエラ・ボリバル共和国",
	"BY":"ベラルーシ",
	"BZ":"ベリーズ",
	"PE":"ペルー",
	"BE":"ベルギー",
	"PL":"ポーランド",
	"BA":"ボスニア・ヘルツェゴビナ",
	"BW":"ボツワナ",
	"BQ":"BES諸島|ボネール、シント・ユースタティウスおよびサバ",
	"BO":"ボリビア|ボリビア多民族国",
	"PT":"ポルトガル",
	"HK":"香港",
	"HN":"ホンジュラス",
	"MH":"マーシャル諸島",
	"MO":"マカオ",
	"MK":"マケドニア共和国|マケドニア旧ユーゴスラビア共和国",
	"MG":"マダガスカル",
	"YT":"マヨット",
	"MW":"マラウイ",
	"ML":"マリ共和国|マリ",
	"MT":"マルタ",
	"MQ":"マルティニーク",
	"MY":"マレーシア",
	"IM":"マン島",
	"FM":"ミクロネシア連邦",
	"ZA":"南アフリカ共和国|南アフリカ",
	"SS":"南スーダン",
	"MM":"ミャンマー",
	"MX":"メキシコ",
	"MU":"モーリシャス",
	"MR":"モーリタニア",
	"MZ":"モザンビーク",
	"MC":"モナコ",
	"MV":"モルディブ",
	"MD":"モルドバ|モルドバ共和国",
	"MA":"モロッコ",
	"MN":"モンゴル国|モンゴル",
	"ME":"モンテネグロ",
	"MS":"モントセラト",
	"JO":"ヨルダン",
	"LA":"ラオス|ラオス人民民主共和国",
	"LV":"ラトビア",
	"LT":"リトアニア",
	"LY":"リビア",
	"LI":"リヒテンシュタイン",
	"LR":"リベリア",
	"RO":"ルーマニア",
	"LU":"ルクセンブルク",
	"RW":"ルワンダ",
	"LS":"レソト",
	"LB":"レバノン",
	"RE":"レユニオン",
	"RU":"ロシア|ロシア連邦",
}

var Country_name_en = map[string]string{
	"IS":"Iceland",
	"IE":"Ireland",
	"AZ":"Azerbaijan",
	"AF":"Afghanistan",
	"US":"United States",
	"VI":"Virgin Islands, U.S.",
	"AS":"American Samoa",
	"AE":"United Arab Emirates",
	"DZ":"Algeria",
	"AR":"Argentina",
	"AW":"Aruba",
	"AL":"Albania",
	"AM":"Armenia",
	"AI":"Anguilla",
	"AO":"Angola",
	"AG":"Antigua and Barbuda",
	"AD":"Andorra",
	"YE":"Yemen",
	"GB":"United Kingdom",
	"IO":"British Indian Ocean Territory",
	"VG":"Virgin Islands, British",
	"IL":"Israel",
	"IT":"Italy",
	"IQ":"Iraq",
	"IR":"Iran, Islamic Republic of",
	"IN":"India",
	"ID":"Indonesia",
	"WF":"Wallis and Futuna",
	"UG":"Uganda",
	"UA":"Ukraine",
	"UZ":"Uzbekistan",
	"UY":"Uruguay",
	"EC":"Ecuador",
	"EG":"Egypt",
	"EE":"Estonia",
	"ET":"Ethiopia",
	"ER":"Eritrea",
	"SV":"El Salvador",
	"AU":"Australia",
	"AT":"Austria",
	"AX":"Åland Islands",
	"OM":"Oman",
	"NL":"Netherlands",
	"GH":"Ghana",
	"CV":"Cape Verde",
	"GG":"Guernsey",
	"GY":"Guyana",
	"KZ":"Kazakhstan",
	"QA":"Qatar",
	"UM":"United States Minor Outlying Islands",
	"CA":"Canada",
	"GA":"Gabon",
	"CM":"Cameroon",
	"GM":"Gambia",
	"KH":"Cambodia",
	"MP":"Northern Mariana Islands",
	"GN":"Guinea",
	"GW":"Guinea-Bissau",
	"CY":"Cyprus",
	"CU":"Cuba",
	"CW":"Curaçao",
	"GR":"Greece",
	"KI":"Kiribati",
	"KG":"Kyrgyzstan",
	"GT":"Guatemala",
	"GP":"Guadeloupe",
	"GU":"Guam",
	"KW":"Kuwait",
	"CK":"Cook Islands",
	"GL":"Greenland",
	"CX":"Christmas Island",
	"GE":"Georgia",
	"GD":"Grenada",
	"HR":"Croatia",
	"KY":"Cayman Islands",
	"KE":"Kenya",
	"CI":"Côte d'Ivoire",
	"CC":"Cocos (Keeling) Islands",
	"CR":"Costa Rica",
	"KM":"Comoros",
	"CO":"Colombia",
	"CG":"Congo",
	"CD":"Congo, the Democratic Republic of the",
	"SA":"Saudi Arabia",
	"GS":"South Georgia and the South Sandwich Islands",
	"WS":"Samoa",
	"ST":"Sao Tome and Principe",
	"BL":"Saint Barthélemy",
	"ZM":"Zambia",
	"PM":"Saint Pierre and Miquelon",
	"SM":"San Marino",
	"MF":"Saint Martin (French part)",
	"SL":"Sierra Leone",
	"DJ":"Djibouti",
	"GI":"Gibraltar",
	"JE":"Jersey",
	"JM":"Jamaica",
	"SY":"Syrian Arab Republic",
	"SG":"Singapore",
	"SX":"Sint Maarten (Dutch part)",
	"ZW":"Zimbabwe",
	"CH":"Switzerland",
	"SE":"Sweden",
	"SD":"Sudan",
	"SJ":"Svalbard and Jan Mayen",
	"ES":"Spain",
	"SR":"Suriname",
	"LK":"Sri Lanka",
	"SK":"Slovakia",
	"SI":"Slovenia",
	"SZ":"Swaziland",
	"SC":"Seychelles",
	"GQ":"Equatorial Guinea",
	"SN":"Senegal",
	"RS":"Serbia",
	"KN":"Saint Kitts and Nevis",
	"VC":"Saint Vincent and the Grenadines",
	"SH":"Saint Helena, Ascension and Tristan da Cunha",
	"LC":"Saint Lucia",
	"SO":"Somalia",
	"SB":"Solomon Islands",
	"TC":"Turks and Caicos Islands",
	"TH":"Thailand",
	"KR":"Korea, Republic of",
	"TW":"Taiwan, Province of China",
	"TJ":"Tajikistan",
	"TZ":"Tanzania, United Republic of",
	"CZ":"Czech Republic",
	"TD":"Chad",
	"CF":"Central African Republic",
	"CN":"China",
	"TN":"Tunisia",
	"KP":"Korea, Democratic People's Republic of",
	"CL":"Chile",
	"TV":"Tuvalu",
	"DK":"Denmark",
	"DE":"Germany",
	"TG":"Togo",
	"TK":"Tokelau",
	"DO":"Dominican Republic",
	"DM":"Dominica",
	"TT":"Trinidad and Tobago",
	"TM":"Turkmenistan",
	"TR":"Turkey",
	"TO":"Tonga",
	"NG":"Nigeria",
	"NR":"Nauru",
	"NA":"Namibia",
	"AQ":"Antarctica",
	"NU":"Niue",
	"NI":"Nicaragua",
	"NE":"Niger",
	"JP":"Japan",
	"EH":"Western Sahara",
	"NC":"New Caledonia",
	"NZ":"New Zealand",
	"NP":"Nepal",
	"NF":"Norfolk Island",
	"NO":"Norway",
	"HM":"Heard Island and McDonald Islands",
	"BH":"Bahrain",
	"HT":"Haiti",
	"PK":"Pakistan",
	"VA":"Holy See (Vatican City State)",
	"PA":"Panama",
	"VU":"Vanuatu",
	"BS":"Bahamas",
	"PG":"Papua New Guinea",
	"BM":"Bermuda",
	"PW":"Palau",
	"PY":"Paraguay",
	"BB":"Barbados",
	"PS":"Palestinian Territory, Occupied",
	"HU":"Hungary",
	"BD":"Bangladesh",
	"TL":"Timor-Leste",
	"PN":"Pitcairn",
	"FJ":"Fiji",
	"PH":"Philippines",
	"FI":"Finland",
	"BT":"Bhutan",
	"BV":"Bouvet Island",
	"PR":"Puerto Rico",
	"FO":"Faroe Islands",
	"FK":"Falkland Islands (Malvinas)",
	"BR":"Brazil",
	"FR":"France",
	"GF":"French Guiana",
	"PF":"French Polynesia",
	"TF":"French Southern Territories",
	"BG":"Bulgaria",
	"BF":"Burkina Faso",
	"BN":"Brunei Darussalam",
	"BI":"Burundi",
	"VN":"Viet Nam",
	"BJ":"Benin",
	"VE":"Venezuela, Bolivarian Republic of",
	"BY":"Belarus",
	"BZ":"Belize",
	"PE":"Peru",
	"BE":"Belgium",
	"PL":"Poland",
	"BA":"Bosnia and Herzegovina",
	"BW":"Botswana",
	"BQ":"Bonaire, Saint Eustatius and Saba",
	"BO":"Bolivia, Plurinational State of",
	"PT":"Portugal",
	"HK":"Hong Kong",
	"HN":"Honduras",
	"MH":"Marshall Islands",
	"MO":"Macao",
	"MK":"Macedonia, the former Yugoslav Republic of",
	"MG":"Madagascar",
	"YT":"Mayotte",
	"MW":"Malawi",
	"ML":"Mali",
	"MT":"Malta",
	"MQ":"Martinique",
	"MY":"Malaysia",
	"IM":"Isle of Man",
	"FM":"Micronesia, Federated States of",
	"ZA":"South Africa",
	"SS":"South Sudan",
	"MM":"Myanmar",
	"MX":"Mexico",
	"MU":"Mauritius",
	"MR":"Mauritania",
	"MZ":"Mozambique",
	"MC":"Monaco",
	"MV":"Maldives",
	"MD":"Moldova, Republic of",
	"MA":"Morocco",
	"MN":"Mongolia",
	"ME":"Montenegro",
	"MS":"Montserrat",
	"JO":"Jordan",
	"LA":"Lao People's Democratic Republic",
	"LV":"Latvia",
	"LT":"Lithuania",
	"LY":"Libya",
	"LI":"Liechtenstein",
	"LR":"Liberia",
	"RO":"Romania",
	"LU":"Luxembourg",
	"RW":"Rwanda",
	"LS":"Lesotho",
	"LB":"Lebanon",
	"RE":"Réunion",
	"RU":"Russian Federation",
}
